CREATE TABLE Kelas(
	KelasId INT IDENTITY(1,1),
	KelasName VARCHAR(50) NOT NULL DEFAULT(''),
	JurusanId INT NOT NULL DEFAULT(0),
	Tingkat INT NOT NULL DEFAULT(0),
	Flag VARCHAR(3) NOT NULL DEFAULT(''),
	
	CONSTRAINT PK_Kelas PRIMARY KEY CLUSTERED(KelasId)
)